version: '3.8'

name: cash-flow
services:
  cashin-cashout:
    build: ./cmd/cashin-cashout/
    ports:
      - "8088:8088"
    depends_on:
      - db
      - keycloak

  # daily-summary:
  #   build: ./cmd/daily-summary/
  #   ports:
  #     - "8089:8089"
  #   depends_on:
  #     - db
  #     - redis
  #     - keycloak

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: database
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"
