version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: cf-postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: cashflow
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  keycloak:
    image: quay.io/keycloak/keycloak:21.0.1
    container_name: cf-keycloak
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command: start-dev
    ports:
      - "8082:8080"
    depends_on:
      - postgres

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"

  cashincashout:
    build:
      context: .
      dockerfile: ./cmd/cashin-cashout/Dockerfile
    container_name: cashin-cashout
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - postgres
      - redis
    ports:
      - "8080:8080"

  dailysummary:
    build:
      context: .
      dockerfile: ./cmd/daily-summary/Dockerfile
    container_name: daily-summary
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - postgres
      - redis
    ports:
      - "8081:8081"

volumes:
  postgres_data:
